### ISSUE TITLE
Properly set default endpoint

### ISSUE THREAD

**Issue by peterthomassen** [desec-io/certbot-dns-desec#14]
With `dns_desec_endpoint` not in my `credentials.ini`, I get
```
Failed to renew certificate peter.dedyn.io with error: Missing property in credentials configuration file /home/peter/git/desec-certs/credentials.ini:
 * Property "dns_desec_endpoint" not found (should be URL of the deSEC API.).
```

This seems to be due to https://github.com/certbot/certbot/blob/30b066f08260b73fc26256b5484a180468b9d0a6/certbot/certbot/plugins/dns_common.py#L142.

**Comment by nils-wisiol** [comment]
Fixed by #15
