### ISSUE TITLE
DNS problem: check that a DNS record exists for this domain

### ISSUE THREAD

**Issue by emvidi** [desec-io/certbot-dns-desec#18]
When creating for the first time a certificate for a subdomain the above error is thrown. 

![swappy-05-02-2022_22:57:39](https://user-images.githubusercontent.com/37313823/152659047-f85f8a12-7173-418c-ac92-812c2dade4fb.png)
[letsencrypt.log](https://github.com/desec-io/certbot-dns-desec/files/8008928/letsencrypt.log)

 On 2nd run everything is ok.

**Comment by nils-wisiol** [comment]
Your log shows that the propagation waiting time is 60s. Unfortunately, desec-stack currently has issues and sometimes cannot provide fast updates. Hence this value needs to be increased as desec-stack is reworking the propagation method. Default is now 80s (b0284b70f1ecf2e7d589ecbdc740e9267bd67d0f).

**Comment by kjartanhr** [comment]
I was having a similar problem, despite the fix posted above. Arbitrarily setting `dns-desec-propagation-seconds` to `300` fixed this after having tried `120` once. Hope this ends up helping someone. But this issue may be worth looking into again.
