### ISSUE TITLE
Plugin Not Compatible with Certbot >= 2.0.0

### ISSUE THREAD

**Issue by Rasmis** [desec-io/certbot-dns-desec#22]
I've had to move servers a lot in the last week, and I've been happy with desec and this plugin.

But today I've moved to a virtual server, with the same setup as before (Debian Bullseye and Apache), and this happened.
```bash
sudo certbot certonly --authenticator dns-desec --dns-desec-credentials /etc/letsencrypt/secrets/desec.ini -d "example.com" -d "*.example.com"
An unexpected error occurred:
AttributeError: module 'certbot.interfaces' has no attribute 'IAuthenticator'`
```

There were no hits on the search engines, so that's why I'm writing this issue. I tried installing, reinstalling, force installing, getting zope, upgrading and downgrading. I'm assuming I'm missing some package, but I can't figure out which. Or maybe it's a permissions problem. I'm no expert. But I did come up with a solution.

The log file (`/tmp/certbot-log-pdhhx7oz/log`) pointed me to the desec plugin. 

```
Traceback (most recent call last):
  File "/usr/local/bin/certbot", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/certbot/main.py", line 19, in main
    return internal_main.main(cli_args)
  File "/usr/local/lib/python3.9/dist-packages/certbot/_internal/main.py", line 1707, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/usr/local/lib/python3.9/dist-packages/certbot/_internal/plugins/disco.py", line 208, in find_all
    cls._load_entry_point(entry_point, plugins)
  File "/usr/local/lib/python3.9/dist-packages/certbot/_internal/plugins/disco.py", line 215, in _load_entry_point
    plugin_ep = PluginEntryPoint(entry_point)
  File "/usr/local/lib/python3.9/dist-packages/certbot/_internal/plugins/disco.py", line 56, in __init__
    self.plugin_cls: Type[interfaces.Plugin] = entry_point.load()
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 2471, in load
    return self.resolve()
  File "/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py", line 2477, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.9/dist-packages/certbot_dns_desec/dns_desec.py", line 16, in <module>
    @zope.interface.implementer(interfaces.IAuthenticator)  # needed for compatibility with older certbots, see #13
AttributeError: module 'certbot.interfaces' has no attribute 'IAuthenticator'
2022-11-24 22:44:33,862:ERROR:certbot._internal.log:An unexpected error occurred:
2022-11-24 22:44:33,862:ERROR:certbot._internal.log:AttributeError: module 'certbot.interfaces' has no attribute 'IAuthenticator'
```

Is `#13` [issue 13](https://github.com/desec-io/certbot-dns-desec/issues/13)? I couldn't see the connection.

This is how I fixed it:
In `/usr/local/lib/python3.9/dist-packages/certbot_dns_desec/dns_desec.py` I commented out these two lines:
```python
#@zope.interface.implementer(interfaces.IAuthenticator)  # needed for compatibility with older certbots, see #13
#@zope.interface.provider(interfaces.IPluginFactory)  # needed for compatibility with older certbots, see #13
```

Now it works. While checking to see if this issue had already been reported, I found [another certbot plugin](https://github.com/obynio/certbot-plugin-gandi/pull/41) with a pull request to remove the zope support. TBH I have no clue what zope is, but for me the plugin works without it.

Now you know. I hope it helps.

**Comment by nils-wisiol** [comment]
Hi @Rasmis, thanks for your detailed report.

#13 indeed refers to issue 13, which refers to commit bb7c4a1aa5b5a1f93e4973267e800285e430b8c4.

Issues with this interface ultimately lead me to introducing tests for different certbot versions: https://github.com/desec-io/certbot-dns-desec/blob/75e847709eaea1109e384a07053bbc676a390c8f/.github/workflows/e2e.yml#L22-L28

Which certbot version are you using?

**Comment by nils-wisiol** [comment]
I see that [certbot 2.0.0 was released](https://pypi.org/project/certbot/#history). Check #23 for extended testing.

**Comment by Rasmis** [comment]
Yes, sorry. Now I know why it worked on the other servers. I used [the desec guide](https://pypi.org/project/certbot-dns-desec/) on all the servers, but this Monday, 2022-11-21, `python3 -m pip install certbot` gets you version 2.0. Where zope doesn't work.

**Comment by nils-wisiol** [comment]
For the time being, I recommend downgrading two certbot<2.0.0 until we figure out a solution. I believe simply removing the annotations will break support for earlier versions (see, again, #13), so it needs to be more complex than that.

I changed the title for others stopping by with similar problems.

**Comment by Rasmis** [comment]
Do you have write access to [the pypi-guide](https://pypi.org/project/certbot-dns-desec/)? We may want to change it. 

According to [this recent issue](https://github.com/certbot/certbot/issues/9480) Certbot doesn't want a system-wide pip install, and their [pip guide](https://certbot.eff.org/instructions?ws=other&os=pip) creates a virtual environment. Considering the version control, that's probably good in this case. 

Here's a complete guide to installing certbot 1.31.0 and certbot-dns-desec on Debian Bullseye:

```bash
# Make sure system is up to date
$ sudo apt update
$ sudo apt install python3 python3-venv libaugeas0

# Make virtual environment with sudo and upgrade pip
$ sudo python3 -m venv /opt/certbot/
$ sudo /opt/certbot/bin/pip install --upgrade pip

# Install certbot, plugin and acme. Acme version needs to match certbot version
$ sudo /opt/certbot/bin/pip install certbot==1.31.0 acme==1.31.0 certbot-dns-desec

# Optional: Link this certbot
$ sudo ln -s /opt/certbot/bin/certbot /usr/bin/certbot

```

**Comment by nils-wisiol** [comment]
> Do you have write access to [the pypi-guide](https://pypi.org/project/certbot-dns-desec/)? We may want to change it.

Yes, the guide is just the README that lives in this repository. Please feel free to create a PR along the lines of what you wrote above! :-)
